name: Scraping Noticias Jurídicas

on:
  schedule:
    # Ejecutar cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  scrape-noticias:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configurar variables de entorno
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> APIS_Y_CREDENCIALES.env
        echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> APIS_Y_CREDENCIALES.env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> APIS_Y_CREDENCIALES.env
        
    - name: Ejecutar scraping
      run: |
        python3 backend/main.py
        
    - name: Notificar resultado
      if: always()
      run: |
        echo "✅ Scraping completado - $(date)"
        echo "📊 Revisar resultados en redjudicial.cl/noticias.html" 